services:
  database:
    image: mysql:8-oracle
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 5050:8080

  frontend:
    image: todo_ui:0.2
    # build:
    # context: ./ui/todo_ui
    #   dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BaseUrl=http://backend:${PORT}
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    image: todo_api:0.2.2 # build: parch version with a waiting script to wait for the database to be ready
      # context: ./server
    #   dockerfile: Dockerfile
    environment:
      - PORT=8000
      - NODE_ENV=production
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    ports:
      - 8000:8000
    depends_on:
      - database
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
volumes:
  db_data:
    driver: local
networks:
  default:
    driver: bridge
