apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
        - name: backend-app
          image: "{{.Values.backend.image.repository}}:{{.Values.backend.image.tag}}"
          pullPolicy: {{.Values.backend.image.pullPolicy}}
          envFrom:
            - secretRef:
                name: app-secret
            - configMapRef:
                name: app-config
          ports:
            - name: backend
              containerPort: {{ .Values.backend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - name: backend
      port: {{ .Values.backend.port }}
      targetPort: backend
