apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: opaque
data:
  MYSQL_USER: "{{.Values.secret.MYSQL_USER}}"
  MYSQL_PASSWORD: "{{.Values.secret.MYSQL_PASSWORD}}"
  MYSQL_ROOT_PASSWORD: "{{.Values.secret.MYSQL_ROOT_PASSWORD}}"
  
